BussinessProject/urls.py
from django.contrib import admin
from django.urls import path, include
from Bussinessapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('Bussinessapp/',include('Bussinessapp.urls')),
]

Bussinessapp/urls.py
from django.urls import path
from . import views
app_name='Bussinessapp'

#Create Your Urls Path here
urlpatterns = [
    path('products/',views.products,name='products'),
    path('contact_us/',views.contact_us,name='contact_us')
]

Bussinessapp/models.py
from django.db import models

#For including phone number field in djangoproject
from phone_field import PhoneField

# Create your models here.
class Customer(models.Model):
    Name = models.CharField(max_length=50, help_text='Your GoodName')
    Email = models.EmailField(max_length=254, blank=True, help_text='abc@gmail.com')
    phone = PhoneField(blank=True, help_text='Contact phone number')
    Address = models.CharField(max_length=524, help_text='Your Address')

Bussinessapp/forms.py
from Bussinessapp.models import Customer
from django import forms

#Create Your Forms here
class Query(forms.ModelForm):
    subject = forms.CharField(max_length=500)
    Message = forms.TextField()

    class Meta():
        model = Customer
        fields = ('Name','Email','Contact_no')

Bussinessapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html',{})


def products(request):
    return render(request,'products.html',{})


def contact_us(request):
    return render(request,'contact_us.html',{})

Bussinessapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Khandelwal Store</title>

    <!-- CSS file link -->
    <link rel="stylesheet" href="{% static 'css/index.css'%}">

    <!-- js file link -->
    <script  type="text/javascript" src="{% static 'index.js' %}">

    </script>

    <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital@1&family=Lobster&family=Montserrat&family=Roboto+Mono:ital@1&display=swap" rel="stylesheet">

    <!-- Font awesome library -->
    <script src="https://kit.fontawesome.com/569aa1fca8.js" crossorigin="anonymous"></script>
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>



    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <!-- Main Navbar -->
  <header>
    <nav>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'index' %}">Khandelwal Trophy's</a>

    <!-- NAVBAR ITEMS TO BE COLLAPSED -->
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'Bussinessapp:products'  %}" aria-disabled="true">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'Bussinessapp:contact_us' %}" tabindex="-1" aria-disabled="true">Contact Us</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  <div class="justify-content-end navbar-brand">
    <ul class="navbar-nav inline">
      <li class="nav-item active"><a data-toggle="tooltip" data-placement="bottom" title="Call" href="tel:9982035408"><i class="fas fa-phone-alt"></i></a></li>
      <li class="nav-item active"><a data-toggle="tooltip" data-placement="bottom" title="Email" href="mailto:khandelwalfancystore01@gmail.com"><i class="far fa-comments"></i></a></li>
      <li class="nav-item active"><a data-toggle="tooltip" data-placement="bottom" title="Facebook" href="https://facebook.com" ><i class="fab fa-facebook-f"></i></a></li>
      <li class="nav-item active"><a data-toggle="tooltip" data-placement="bottom" title="Whatsapp" href="https://api.whatsapp.com/send?phone=919982035408" target="_blank"><i class="fab fa-whatsapp"></i></a></li>
    </ul>
  </div>
</nav>
    </nav>
    <!-- NAVBAR ENDS -->
  </header>

  <body>
    {% block body_block %}

    {% endblock %}



  </body>
</html>

Bussinessapp/templates/contact_us.html
{% extends 'base.html' %}
{% block body_block %}
<h1>bjkbcmsn</h1>
<h1 class="animate__animated animate__bounce">An animated element</h1>
{% endblock %}

Bussinessapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<!-- CAROUSEL SLIDER -->


<!-- INDICATORS -->
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>

  </ol>
  <!-- first slide -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/trophy1.jpg' %}" class="d-block w-100" alt="..." style="height:450px;width:100%">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="animate__animated animate__lightSpeedInRight">We Export High Quality of Products</h3>
        <button type="button" name="Button" href="{% url 'Bussinessapp:products' %}">View Products</button>

      </div>
    </div>
    <!-- second slide -->
    <div class="carousel-item">
      <img src="{% static 'images/trophy2.jpg' %}" class="d-block w-100" alt="..." style="height:450px;width:100%">
      <div class="carousel-caption d-none d-md-block">
        <h3 class="animate__animated animate__lightSpeedInRight">Alwar's Best Stop Shop For Trophy's!</h3>
        <h3 class="animate__animated animate__lightSpeedInRight">Acrylic Trophy, Fibre Trophy etc</h3>
      </div>
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




{% endblock %}

Bussinessapp/templates/index1.html
<div id="carouselExampleIndicators" class="carousel slide">
     <ol class="carousel-indicators">
       <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
       <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
       <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
     </ol>
     <div class="carousel-inner skyblue">

       <!-- first slide -->
       <div class="carousel-item active skyblue">
         <div class="carousel-caption d-md-block">
           <h3 class="animate__animated animate__zoomOutUp">
             This is the caption for slide 1
           </h3>
           <h3 class=" animate__animated animate__zoomOutLeft">
             This is the caption for slide 1
           </h3>
           <button class="btn btn-primary btn-lg" class=" animate__animated animate__zoomOutLeft">Button</button>
         </div>
       </div>

       <!-- second slide -->
       <div class="carousel-item skyblue">
         <div class="carousel-caption d-md-block">
            <h3 class="animate__animated animate__zoomOutUp">
             <span class="fa fa-heart animate__animated animate__zoomOutUp"></span>
           </h3>
           <h3 data-animation="animated bounceInUp">
             This is the caption for slide 2
           </h3>
           <button class="btn btn-primary btn-lg" data-animation="animated zoomInRight">Button</button>
         </div>
       </div>

       <!-- third slide -->
       <div class="carousel-item skyblue">
         <div class="carousel-caption d-md-block">
           <h3 class="icon-container" data-animation="animated zoomInLeft">
             <span class="fa fa-glass"></span>
           </h3>
           <h3 data-animation="animated flipInX">
             This is the caption for slide 3
           </h3>
           <button class="btn btn-primary btn-lg" data-animation="animated lightSpeedIn">Button</button>
         </div>
       </div>
     </div>

     <!-- controls -->
     <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
 <span class="carousel-control-prev-icon" aria-hidden="true"></span>
 <span class="sr-only">Previous</span>
</a>
     <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
 <span class="carousel-control-next-icon" aria-hidden="true"></span>
 <span class="sr-only">Next</span>
</a>
   </div>

Bussinessapp/templates/products.html
{% extends 'base.html' %}
{% block body_block %}
{% endblock %}